development:
  adapter: mysql2
  host: localhost
  encoding: utf8
  database: depot
  user: root
  password: rjvbccfh

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: localhost
  encoding: utf8
  database: depot
  user: root
  password: rjvbccfh
